DEFINES+=PROJECT_CONF_H=\"project-conf.h\"

# all: mqtt-example
all: node1

APPS += mqtt

# Linker size optimization
SMALL = 1

CONTIKI_WITH_IPV6 = 1

# CONTIKI = /home/fito/contiki
include ../contiki.location

include $(CONTIKI)/Makefile.include
